---
- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: absent

  - name: Insert Index Page
    template:
      src: /root/nitesh.repo/master/host_vars/index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
